### ISSUE TITLE
CFG Lock Quirks

### ISSUE THREAD

**Issue by csmtr** [balopez83/macOS_On_Hyper-V#10]
Disable the CFG Lock related quirks since Hyper-V already has it disabled by default! [AppleCpuPmCfgLock; AppleXcpmCfgLock] I am currently updating the plist and everything in your VHDX for better support, audio and related features. I would like you to create a fork to this repo of the opencore x64 folder and everyone could start updating it, to help you out. No need to share binaries, just the folder structure including the text files as plist and other, the binaries you would give in the releases tab in the vhdx as you been doing.

**Comment by balopez83** [comment]
@cosmitir Please see "EFI-Testing" branch. Currently there is only a clean EFI in there and as is would not boot Hyper-V. I am using macOS at the moment and haven't had a chance to flip over to Windows to pull the EFI config from the latest release VHDX. Let me know if that works for you or if you need anything else done to help with this.

**Comment by balopez83** [comment]
Added config.plist with current release configuration to the fork

**Comment by cosmitir** [comment]
Thank you, i am just finishing some tests, do you want a better tutorial too on how to setup everything?

**Comment by balopez83** [comment]
I am open to it all. Thanks for contributing

**Comment by cosmitir** [comment]
Btw i was going to improve this, but i found out that someone already got all the work done, and since there isnt really an advantage on running macos virtualized, i guess this could just be for people try out opencore and mac before trying it on baremetal. Check this https://github.com/Qonfused/OSX-Hyper-V
About the audio support, at some time, it looked like i got any progress, but the final result is still not working, and far as i can see, there is no need for audio in a virtual machine! Hope this helps you out if you want to improve the repo, there are a lot of fixes to do on your plist and efi folder, most of them you will find in the hyper-v kext repo, you had some device properties that arent in need, i did manage to find some bad configured quirks, if you want i can send you my final plist and you work from there. That is all for now. Anything else, contact me on discord: cosmitir

**Comment by balopez83** [comment]
Thank you for the information. I will check out that repo. It looks like that one might have also been successful in booting legacy 10.4-10.6 which I was not able to. 

The config on my repo is cluttered as I am aware; I left my testing stuff in there as I was working on an attempt to get the VMware graphics kext to work in Hyper-V among other things. The VMware kext improves VESA graphics to give it more memory and make things a bit smoother when using VMware to virtualize macOS. In order to do that however you need a device for it to attach to which is why there are devices that don't belong. I had not finished spoofing it or correctly defining the actual graphics device but it's on my list of things to attempt. It is currently a simple copy over of the device for VMware but should be disabled to avoid issues.

You're certainly correct about the performance when virtualizing. I believe this Hyper-V project was likely started as a result of Apple's dumping of Intel and likely to attempt to provide better performance than what is provided in VMware or Virtual Box when virtualizing. Additionally, it opens up the possibility of virtualizing legacy 10.4-10.6 macOS which won't permit installation as a virtual Machine but would in Hyper-V as it looks like bare metal to macOS. Plus unless you have an old Core Duo machine lying around it's almost impossible to get those legacy versions running and even then it's near impossible. I have an old Vaio from that era and the lowest I can get installed is Snow Leopard even though it should support down to 10.4. 

If you are feeling adventurous and would like to try something, I could use your help. I want to attempt to get OpenDuet working on a Gen 1 Hyper-V. The reason for this is that with OpenDuet you can specify the ForceResolution quirk and specify a resolution. Since Hyper-V won't let you specify the default resolution in Gen 2 (UEFI based) and ForceResolution does not work yet outside of using OpenDuet the resolution of the Hyper-V is extremely small. If we could get the legacy OpenCore/OpenDuet working in a Gen 1 (Bios based) Hyper-V then we could potentially force the resolution to something larger and make Hyper-V more useful. 

To start working on this you would want to look at the legacy OpenCore instructions for installing on a BIOS based machine and convert them as appropriate for a VHD. I got stuck attempting to actually make the VHD bootable. I was successful getting this working on an old BIOS based Sony Vaio (see my other repo) and was able to force the resolution which macOS respected (where it did not before the ForceResolution quirk was available).

If you can figure out how to make the VHD boot to OpenCore, I believe I can take it from there to integrate everything else.

**Comment by balopez83** [comment]
@cosmitir So I finally had a chance to look at the EFI you linked and it is pretty good however I did notice some issues with it. Two things right off the bat are missing CPU spoofing so users of 11th gen and later CPU's cant use it unless they know how to manually spoof and also battery status support. There are a few other things but those are the two most obvious. 

I have just issued another release which should be a good balance between the two removing the unneeded items you pointed out but keeping the needed items for full support. 

Not sure if you are still using hyper-v but if you are its worth looking at. I intend to issue another release soon which will add a lot of additional support beyond what is included in the other repo.
