### ISSUE TITLE
Can not boot on Intel i7 12700h cpu

### ISSUE THREAD

**Issue by amirjahani** [balopez83/macOS_On_Hyper-V#18]
![Untitled](https://github.com/balopez83/macOS_On_Hyper-V/assets/42303786/f80edfdd-8cd5-40e6-883f-3d58f6e4218b)

**Comment by balopez83** [comment]
@amirjahani I need more information. Did you set the VM specs per the instructions? The VM requires at least 8gb of ram and based on most the issues people experience booting is almost always because too little ram was assigned.

Please confirm all settings are set exactly as described in the instructions? Any variation can cause a boot failure.

**Comment by janek515** [comment]
Having the same issue. Windows 11 i5-1340P 4 vCPU 8GB RAM. Set up twice as described in the instructions and didn't get to the recovery UI.

**Comment by balopez83** [comment]
@janek515 I think there may be an issue that needs to be resolved to make this EFI more compatible with more systems. I'm limited on time currently but I will try and get a new release out in the next few weeks.

Also make sure you didn't accidentally leave checkpoints enabled. It is notorious for messing up the boot process and damaging the vm. Not sure that's it but worth double check

**Comment by janek515** [comment]
Spoofing the cpuid is what did it for me. https://github.com/acidanthera/bugtracker/issues/2179#issuecomment-1572945606

**Comment by balopez83** [comment]
@janek515 It should have already been spoofed. Unless I accidentally forgot to put the right config up it should have been spoofed already to allow 11gen and newer to run. Did the config not have any spoofing in those sections cause if not I need to add that back in.

**Comment by janek515** [comment]
it had but iirc the values were different

**Comment by balopez83** [comment]
I'm glad it worked but surprised that fixed it. Usually that presents as a problem earlier in the boot process and not after the kernel begins to load. 

The Cupid I used was to enable legacy OS support as well so it's possible that's where the issue is. My older releases used the Cupid in the link you provided. 

My next release is being built from the ground up anyway and will most likely break out legacy vs recent OS versions and so these issues shouldn't be a problem anymore. 

I believe there has been some configuration issues as well with some of the vms and so I'm going to try to add a default working config that should ensure people can get up and running faster with less issues.

**Comment by balopez83** [comment]
@janek515 @amirjahani Added a new release that may resolve the issue experienced. Not sure if it will fix it but wanted to get a fix out there quickly due to all the issues people have had with the previous release. Please let me know if this resolves your issues.

**Comment by cguo2013** [comment]
both 12th and 13th Gen intel CPU can spoof as below:

		<key>Emulate</key>
		<dict>
			<key>Cpuid1Data</key>
			<data>VQYKAAAAAAAAAAAAAAAAAA==</data>
			<key>Cpuid1Mask</key>
			<data>/////wAAAAAAAAAAAAAAAA==</data>

**Comment by balopez83** [comment]
Ending support and archiving this repo. Please see https://github.com/Qonfused/OSX-Hyper-V as that project is actively maintained and has greater support. 

I no longer have a Hyper-V capable machine and so it is challenging to support and ensure that any future updates will work properly. Archiving for anyone that still wants to use the files or reference any of the issues.
