### ISSUE TITLE
Request help

### ISSUE THREAD

**Issue by r3x5ur** [balopez83/macOS_On_Hyper-V#21]
- **I installed it step by step according to your guide, but**
- I've been stuck on this interface for more than 14 hours
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/64947085/2e014131-5d74-4eb4-a70d-fdc9fb12375a)

- This is my virtual machine configuration
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/64947085/212e410b-7177-48aa-91bd-b398978d98cb)

- Is it because I can't get the IP address here that it's stuck?
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/64947085/d9048ff9-a61c-46d2-86f3-d360da9a545c)

**Comment by r3x5ur** [comment]
@balopez83 Is there any way to solve it? I've been stuck many times.
**_Can you help me. Thanks_**

**Comment by r3x5ur** [comment]
- My hardware information
- CPU `i5-10400F`
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/64947085/43d0a8c1-144d-44f1-a07a-0222fe48fd58)

**Comment by balopez83** [comment]
@r3x5ur I don't think it's related to the IP address. 

Is your issue occurring with the recovery before you installed macOS or is that after installation?

Did you edit the config. Plist at all? If so what did you edit?

Can you add -v to the boot args so that it shows the verbose code and screenshot your boot up for me so I can see where it is freezing?

I am seeing a lot of issues booting so I think I may need to make some changes and issue a new release. I don't have a ton of time currently so it may be a few weeks before I can issue a release to fix this, assuming your issue is related at all to the issues others are having.

**Comment by r3x5ur** [comment]
@balopez83 
- It got stuck the first time I opened it.
- I haven't moved config. plist, because I don't know much about this aspect
- Where is the-v parameter added?

**Comment by r3x5ur** [comment]
Add - v args here?
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/64947085/d31ad70c-330b-4c53-808f-f60057344e5e)

**Comment by r3x5ur** [comment]
There are many errors..
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/64947085/56b93997-be20-49b5-b681-400345f20219)

**Comment by r3x5ur** [comment]
The main reason should be _**busy timeout[0],  (240s): 'VMBS' (a,4020001 )**_

**Comment by balopez83** [comment]
What version of macOS did you try to install? 

Is there any chance you left snapshots/checkpoints turned on in Hyper-v? I've seen those errors before when I have accidentally left it on. It can mess it up bad enough that I have had to delete the drive and start with a clean one when I've made that mistake.

**Comment by r3x5ur** [comment]
Later I restarted my computer and used https://github.com/cidanthera/bugtracker/issues/2179#issuecomment-1638161636
Now I can log in, but the https://support.apple.com/mac/startup error appears.

**Comment by r3x5ur** [comment]
After many retries, it finally worked
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/64947085/edc817c3-a552-43af-b0d8-29ae04b46678)

Can the graphics card be upgraded? It’s very slow.

**Comment by balopez83** [comment]
@r3x5ur I am glad you were able to get it up and running. 

Unfortunately macOS on Hyper-v is in very Alpha stages at this time. There is no graphics pass through much like when using macOS on VMWare and so macOS runs in what is called vesa mode. Because of this graphics is very slow and there is no solution until the acidanthera group develops a graphics driver.

You have a tenth gen computer which means your computer is very likely fully compatible with macOS to install it bare metal (like windows). I would recommend you do that instead of virtualizing which will give you a much better experience. You would need to look online and see if you can find any guides or prebuilt EFI folders for your machine otherwise you would need to create your own. Everything you need to create your own can be found in the very detailed dortania OpenCore guide online.

**Comment by balopez83** [comment]
@r3x5ur Added a new release that may resolve the issue experienced. Not sure if it will fix it but wanted to get a fix out there quickly due to all the issues people have had with the previous release. Please let me know if this resolves your issues.

**Comment by r3x5ur** [comment]
@balopez83 thank you very much for your help.
- I installed MacOS just for temporary use
- Windows' rdp can directly use the client's graphics card, but Mac does not seem to support this operation.
- The graphics card driver of my previous device was broken, but I used rdp to connect and it worked fine.

**Comment by balopez83** [comment]
@r3x5ur I believe I understand. macOS definitely doesn't like the RDP protocol and it's very difficult to make that happen. While you can use a Mac with RDP to view windows or Linux it doesn't play well when trying to remote into a Mac. Most people use a VNC application and that works well. Also chrome has an option for remote controlling a desktop that might work better graphics wise but I am not entirely sure. 

In my experience though trying to get the RDP protocol working is unreliable at best. In the end it won't be any faster than using Hyper-v as macOS still won't have a graphics chipset to work on to provide the graphics on your screen. Chrome screen sharing might work better only because chrome uses a lot of software based rendering which might actually be better tuned for what I think you were trying to accomplish.

Hope this helps you a little

**Comment by balopez83** [comment]
Never mind, don't try the chrome Remote Desktop as it is far slower.

**Comment by r3x5ur** [comment]
> Never mind, don't try the chrome Remote Desktop as it is far slower.

Hahaha..  I was about to give it a try, so forget it.
