### ISSUE TITLE
Unable to Boot Issue

### ISSUE THREAD

**Issue by MrBogger** [balopez83/macOS_On_Hyper-V#25]
Good morning,
I have a DellR720xd Home Server currently with 2x E5-2630L processors, Windows 10 Pro 22H2. I've been trying to install MacOS into HyperV but getting stuck at the same place everyone else is with an unsupported processor. I first tried making EFI folder using EliteMacx86 instructions, but the VM wouldn't start. I used your 2.3.0 and 2.3.1 images and they are both getting stuck at the same point. I have also tried MacOS Ventura  and Monterey installations using MacRecovery.py. I have tried recreating the .vhdx image in case there was something not right. I have also been giving the VM 16381MB RAM and no checkpoints. I have left it overnight in case it was still processing but no changes. I have uploaded my UEFI.vhdx into Google if you don't mind having a look and seeing what I'm doing wrong. I also don't require iServices, Audio, Video upgrades etc as I'll be connecting to it through ARD. I also have a MacBook Pro running Monterey as my daily.

https://drive.google.com/drive/folders/1Nx87PVD13pC0JgwG2I0_2IzXHQNYBqkR?usp=sharing

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/32661657/d9d34b48-7193-43bc-a2d8-76d5ea611414)

**Comment by balopez83** [comment]
@MrBogger 

I'm sorry to hear you are also having these issues. 

Currently the hyper-v support provided by acidanthera's kexts is extremely limited. The processors they support I believe are limited to standard Intel processors not including the pentium, Xeon, and celeron processors. 

Some users, including myself have been successful in getting 10th gen standard Intel chips and newer to work but that requires spoofing which has already been implemented. 

I do believe that in a bare metal install Xeon chips can be supported still with spoofing but unlike in hyper-v, it should still work. 

Additionally, depending on your setup, you may have greater success using docker. There is a repo that has a fully supported docker install and I think it has much better support than is currently available with Hyper-v. https://github.com/sickcodes/Docker-OSX

Unfortunately Hyper-v support is in an extremely alpha stage. As support for a broader range of chipsets are available I will add that support here.

One last thing. Some users have had success with the following repo, getting some support on various Intel processors https://github.com/Qonfused/OSX-Hyper-V . While I know it also has its issues, you could give it a go and see if it will work. I believe the issue comes down to the current state of OpenCore and kext support in hyper-v but it might be worth a shot.

**Comment by Havoc918** [comment]
I'm getting stuck at the same spot. Running Windows Server 2019 with 2 x Intel Xeon E5-2660.

**Comment by balopez83** [comment]
@Havoc918 As I mentioned to MrBogger, I believe the Xeon processors are not supported currently due to a lack of support with the kexts currently developed. This isn't something that I can fix and depends on support added to the hyper-v kexts developed by acidanthera.

**Comment by MrBogger** [comment]
Hey Balopez83,

My apologies, I was meant to come back and reply with where I went and what I found chasing this problem. I went down the Linux KVM rabbit hole and found Windows 10 doesn’t support the required packages to allow KVM (or just MacOS) machines under WSL. Apparently upgrading to W11 fixed this but I’m still running unsupported hardware and not interested in upgrading like the rest of the planet. I also tried Docker and failed. I could get one running in VBox but could only allocate 1 CPU core and was useless. The next option I was going to try was under Proxmox directly but then I’d have to rebuild the entire os of my server. My reason for wanting a MacOS VM on my server was for a particular program for video converting media and take the pressure off my MacBook but I’ve now gone away from that idea and jumped on the Unmanic bandwagon.
