### ISSUE TITLE
Not enough RAM in my physical computer

### ISSUE THREAD

**Issue by lehuykhoi2612** [balopez83/macOS_On_Hyper-V#31]
**My physical computer has 8 GB RAM only, but 7.6 GB RAM is usable. So if i adjust the memory of the virtual machine to 8 GB, i will get a memory available is not enough error, how can i fix it?
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/98208711/47c5cd9e-0c6c-4051-a22f-1e68dd49b19e)
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/98208711/4c40b15b-f26d-422b-bb69-a61e09c8dffa)
My apology for the windows display language, but i'm a vietnamese. So, "Bộ nhớ" is RAM.
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/98208711/408cc7a6-8d08-4413-8fc1-ac53f750ba85)**

**Comment by lehuykhoi2612** [comment]
**NOTE THAT I DON'T WANT TO SPEND MONEY TO FIX (E.G INSTALLING NEW RAM TO MY PHYSICAL COMPUTER)**

**Comment by balopez83** [comment]
@lehuykhoi2612 Windows reserves a lot of memory for things in the background. Despite it appearing to be free it generally isn't. 

That error occurs because it simply can't allocate 8gb to the vm. As a general rule you should never allocate more than 50% of your ram to a vm and so in your case 4gb. 

I'm sorry to say there is no way around this short of using a VMware or Virtualbox guide for installing macOS and assigning 4gb only to the vm. 

Using a system with only 8gb is tough with a lot of VMs but you will have a much better experience using VMware on your machine. Hyper-v just won't work to run macOS on your machine.

I'm sorry I don't have better news but at least there is other options.
