### ISSUE TITLE
Serial Number

### ISSUE THREAD

**Issue by jydareau** [balopez83/macOS_On_Hyper-V#33]
HI
No Serial Number , Unable to enroll to Intune
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/35132962/9b033884-ea73-4163-956f-796357b4a2e4)
Thank for help

**Comment by balopez83** [comment]
@jydareau you need to generate your own serial information and place it inside the config.plist in the OpenCore folder. You must follow the guide here https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios which is the main guide for all things OpenCore. 

On a side note I would highly advise against enrolling this in intune. Hyper-V is highly unstable and is not suitable as a daily driver install. Intune can break the install. 

For a more stable installation and especially if you are going to attempt managing the install with services like intune, I would recommend using VMware or Virtual Box for macOS. There are a lot of guides on the web that can guide you through that installation.

Since this is not an issue with the release itself I am closing the issue however you or more than welcome to respond and/or reopen the issue if you have further issues.
