### ISSUE TITLE
serial number showing as unknown even after editing config.plist

### ISSUE THREAD

**Issue by chubbychester** [balopez83/macOS_On_Hyper-V#36]
I dismounted the efi and put in a value for `SystemSerialNumber`. However when I eject it and open the VM it still shows as unknown. I also went to advanced system report and noticed the UUID did not match that of config.plist, any ideas as to why? How to I changed the hardware IDs/serials to make it look like a real Mac?

My Config file
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/169210767/13903949-e172-44f7-b7de-f66fade25618)

System Info: 
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/169210767/591a4ea5-f9bb-4ecb-ae04-1a7169fb3262)

**Comment by balopez83** [comment]
@chubbychester I'm not entirely sure but something is wrong with your set up as far as I can tell. 

Based on your screenshot macOS is seeing your Hyper-v hardware info and not being fed the fake Mac information from the config.

The way you worded your steps make it sound like you somehow dismounted, edited, and then mounted the EFI, but possibly didn't shut down the VM completely (not pausing). macOS must "cold boot" in order to get the new config information.

Hope that helps

**Comment by balopez83** [comment]
@chubbychester Make sure you follow this guide completely to ensure you have the serial information correct. 

https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios

**Comment by chubbychester** [comment]
Hi I completely reinstalled this time without modifying the config.plist but it still doesnt even read the name of the model correctly. My VM folder looks like this and I set this up using this guide https://www.youtube.com/watch?v=qjpOjjqHyXg

my VM folder https://www.youtube.com/watch?v=qjpOjjqHyXg

**Comment by balopez83** [comment]
@chubbychester if you don't put any serial information in then it is expected that it of course won't work the way you expect. The config as is does not have serial information and so OpenCore will pass through the real Hyper-v information. You must add serial information as linked in the guide I linked above and make sure you cold boot your machine and then it should work.

**Comment by chubbychester** [comment]
I didnt put in the serial information just to test if the model name was even being passed through but it appears not to be. Even with the config.plist at default it shows MICROSFT0,1 as the model identifier instead of iMac8,1

**Comment by balopez83** [comment]
@chubbychester I watched the video and while everything is done correctly they did not show how to properly get and add the serial information. You must follow the guide I linked to properly generate and store the serial information. If any one of the values is off in the config OpenCore will not validate them and will NOT pass those values to macOS. Your issue is unlikely anything more than incorrect serial information.

**Comment by balopez83** [comment]
@chubbychester Again that is expected. That is the computer identifier of Hyper-v which macOS is reading. OpenCore won't pass through the rest of the information unless you have a properly configured config as is described in that link I sent you.

**Comment by chubbychester** [comment]
alright using the link you sent, I followed instructions and used GenSMBIOS to create legitimate serials like shown here 
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/169210767/fc17a91b-fc26-4716-bf94-afb59de2935e)
However still no change on the OS itself and no info its being passed

**Comment by chubbychester** [comment]
its worth noting the serial information is correct, I check the serial against Apples website and it told me it was real

**Comment by chubbychester** [comment]
@balopez83 I got it fixed. I used the swapped out the EFI from the current version to the previous version from October and that fixed it. It seems to be a bug with the latest release since the last release it works just fine
