### ISSUE TITLE
In Memory Panic Stackshot Succeeded

### ISSUE THREAD

**Issue by Mirror995** [balopez83/macOS_On_Hyper-V#4]
I followed your instruction. However when I tried to boot the installer, I got a panic. Any approach to fix it?
![屏幕截图 2022-12-15 003306](https://user-images.githubusercontent.com/51252864/207655144-0cf137fd-b809-4c37-9f1b-b168748238ed.png)
Here's my screen recording. The platform I'm using is Intel Xeon E3-1230 v3.
[video.zip](https://github.com/balopez83/macOS_On_Hyper-V/files/10229835/video.zip)

**Comment by Mirror995** [comment]
I will use VMware instead.

**Comment by balopez83** [comment]
Hi @Mirror995 apologies for the delay responding to your issue, I have been super busy with work and haven't been able to focus on these projects. 

I believe your issue is likely a result of incorrect CPU spoofing. The config.plist is spoofed for an 11th gen intel and may need to be changed to spoof properly for a Xeon. I am not sure of the exact spoof code needed but you should be able to find that information in the OpenCore instruction PDF found in the releases zip files. 

Alternatively, if you are attempting to boot Monterey or newer in Hyper-V it could be the reason for your panic. I have not been successful yet booting those versions as they require different kexts and config.plist settings. Once things slow down for me again I will work on updating this repo for those versions and it may resolve this issue. You could try looking at the config.plist linked in this [issue](https://github.com/balopez83/macOS_On_Hyper-V/issues/3) to see if those settings will get yours booting properly.
