### ISSUE TITLE
Support for AMD CPU

### ISSUE THREAD

**Issue by Arturbc** [balopez83/macOS_On_Hyper-V#5]
After follow installation guide, on step of start VM, on starts of install, this stay many time freezed on terminal and never starts the installer.

Note: Create a HFS+ ISO is not loaded on Hyper-V and can't start the VM. To work for me I needed to create a VHDX MacOS installer.

Note 2: VHDX with installer created by MacOS on VMware with CPU patch in .VMX for work Apple S.O. in AMD.

Thanks by your work!

**Comment by balopez83** [comment]
Hi @Arturbc Hyper-V exposes the bare metal specs to macOS and so similar to a true hackintosh AMD cpu's tend to have issues when used to run macOS. You will want to see if there are similar AMD cpu's to yours that are used as hackintoshes and see if there are any custom kexts or CPU/Graphics spoofs that may need to be added to the config.plist to get it to boot. Unfortunately, I do not have an AMD system to test on and so will not be able to help much with this issue. 

You may be best suited using VMware currently as Hyper-V is still very alpha even for Intel computers and is unreliable at best.

**Comment by Arturbc** [comment]
Thanks by response.

I tried use tricks from AMD OS X Hackintosh, but without success. Too hard for me edit the config.plist of OpenCore to set correct flags and get correct custom kexts.

For me is only for hobby and knowledge. Waiting the future of this project.

Thanks one more time.

**Comment by balopez83** [comment]
@Arturbc I have been working on the Hyper-V images a bit more. After a lot of research AMD processors are still not supported at this time. It looks like more work will need to be done with they Hyper-v support kexts and OpenCore before this support can be achieved in Hyper-V. Since this is out of my control and developed by others, I will have to wait till support is added with that software before I can add support to the releases here.
