### ISSUE TITLE
Installer halts due to fatal error

### ISSUE THREAD

**Issue by wengland02** [balopez83/macOS_On_Hyper-V#7]
This pops up when I try to boot the installer. I followed the instructions and spoofed the CPUID and turned Secure Boot off. I am using Windows 11. Any solutions?

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/95513176/15ce65dd-ac68-482f-8e26-3dad7b22fd5e)

**Comment by wengland02** [comment]
Closed because it turns out my CPU is a Tiger Lake CPU and would not work otherwise.

**Comment by balopez83** [comment]
@wengland02 Tiger lake actually should work fine. That error is because there is something wrong with the config.plist file. 

How did you edit the config? By default the config should work with 11th gen and newer cpus though if you edited with OpenCore configurator and didn't use the version matching the OpenCore version in the vhdx it will fail.

**Comment by balopez83** [comment]
That error specifically is an OpenCore error and not macOS

**Comment by balopez83** [comment]
Specifically all Intel cpus should work fine but graphics acceleration won't.

As of now no AMD based CPUs will work.

**Comment by wengland02** [comment]
I edited it using ProperTree. I decided to start fresh and made some changes. I updated some of the OpenCore files and did a clean OC snapshot. It still fails but it looks different. I'll provide my config.plist file. 

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/95513176/0adc2d27-f2e7-467e-9872-eb0ac549f588)

https://drive.google.com/file/d/1NfC_gQxtsKYGx8LvXQUQZmmjszC8MOGw/view?usp=drive_link

**Comment by balopez83** [comment]
@wengland02 So I reviewed your config.plist and unfortunately there are a lot of errors. Despite the clean snapshot ProperTree does not always order the kext properly. It is looking to order them based on a traditional hack and Hyper-V is different. Additionally you have some kexts active that should not be active and you dont have limits on OS versioning. For example both the Hyper-V kexts should be active but limited based on OS. Your current setup would in theory only boot Catalina and lower. 

I know in the world of hacking there is a desire to always have the latest version of OpenCore and kexts. While this is great and I do it myself on my hacks, it does not work well for Hyper-V in this very early stage in development. I would highly recommend that you simply use my release as later versions of OpenCore and kexts do not really add any feature or benefit from the current release. After looking at the changes in the hyper-v kexts there are no functional changes in the patching and so you can use my release and drop in the updated kexts. 

I will be honest, I did not review beyond the kext section since I am currently at work but I can see that you did not exactly match the settings and patches which is why your system is not booting. If you still want to use the latest version of OC you must exactly match every option in the OC config from my version to the latest version. My guess is the reason your system wont boot is likely because you have differences in the UEFI section though the entire configs settings must be identical or it wont boot all the way to macOS. Hyper-V is highly particular and so you cannot follow any traditional getting started guide for a typical hackintosh. Those will always fail. 

Hope this helps you get going. Happy to help where I can

**Comment by balopez83** [comment]
@wengland02 I will prob go ahead and update the repo within the next few days. This EFI is still pretty current but to minimize issues like what you are having its easier for me to just update it.

**Comment by balopez83** [comment]
@wengland02 I have issued a new release version 2.3.0 which updates all kexts and OC to their official release versions. It also adds new support for battery information when running macOS on Hyper-V on a laptop.

Closing this issue since the issue you had should be resolved by using the release config.plist and updated UEFI.vhdx. 

Let me know if you have any further issues or questions.
